# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'prefire' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for prefire
  pod 'Google-Mobile-Ads-SDK'

  target 'prefire-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'prefireTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'prefire-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for prefire-tvOS

  target 'prefire-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
